function f = ND_solutions(x,ica,M)
f = [];
disp(x);
Ind = floor(size(x,1)/10);
Remainder = mod(size(x,1),10);
Start = 1;
[f1,ind,~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p1=x(Start:Ind,1:end);
p1=p1(ind,:);
p1 = p1(1:numel(f1(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('1 of 10 sorted...');
[f2,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p2=x(Start:Ind,1:end);
p2=p2(ind,:);
p2 = p2(1:numel(f2(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('2 of 10 sorted...');
[f3,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p3=x(Start:Ind,1:end);
p3=p3(ind,:);
p3 = p3(1:numel(f3(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('3 of 10 sorted...');
[f4,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p4=x(Start:Ind,1:end);
p4=p4(ind,:);
p4 = p4(1:numel(f4(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('4 of 10 sorted...');
[f5,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p5=x(Start:Ind,1:end);
p5=p5(ind,:);
p5 = p5(1:numel(f5(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('5 of 10 sorted...');
[f6,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p6=x(Start:Ind,1:end);
p6=p6(ind,:);
p6 = p6(1:numel(f6(1).pts(:,3)),:);Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('6 of 10 sorted...');
[f7,ind,~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p7=x(Start:Ind,1:end);
p7=p7(ind,:);
p7 = p7(1:numel(f7(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('7 of 10 sorted...');
[f8,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p8=x(Start:Ind,1:end);
p8=p8(ind,:);
p8 = p8(1:numel(f8(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('8 of 10 sorted...');
[f9,ind, ~] = Non_dominated_sorting(x(Start:Ind,1:end),ica,M);
p9=x(Start:Ind,1:end);
p9=p9(ind,:);
p9=p9(1:numel(f9(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(x,1)/10);
disp('9 of 10 sorted...');
% [f10,ind,~] = Non_dominated_sorting(x(Start:Ind+Remainder,1:end),ica,M);
% p10=x(Start:Ind,1:end);
% p10=p10(ind,:);
% p10 = p10(1:numel(f10(1).pts(:,3)),:);
% disp('10 of 10 sorted...');

P = p1;
P(size(P,1)+1:size(P,1)+size(p2,1),:) = p2;
P(size(P,1)+1:size(P,1)+size(p3,1),:) = p3;
P(size(P,1)+1:size(P,1)+size(p4,1),:) = p4;
P(size(P,1)+1:size(P,1)+size(p5,1),:) = p5;
P(size(P,1)+1:size(P,1)+size(p6,1),:) = p6;
P(size(P,1)+1:size(P,1)+size(p7,1),:) = p7;
P(size(P,1)+1:size(P,1)+size(p8,1),:) = p8;
P(size(P,1)+1:size(P,1)+size(p9,1),:) = p9;
% P(size(P,1)+1:size(P,1)+size(p10,1),:) = p10;
Ind = floor(size(P,1)/5);
Remainder = mod(size(P,1),5);
Start = 1;
[f1,ind,~] = Non_dominated_sorting(P(Start:Ind,1:end),ica,M);
p1=P(Start:Ind,1:end);
p1=p1(ind,:);
p1 = p1(1:numel(f1(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(P,1)/5);
disp('1 of 5 sorted...');
[f2,ind, ~] = Non_dominated_sorting(P(Start:Ind,1:end),ica,M);
p2=P(Start:Ind,1:end);
p2=p2(ind,:);
p2 = p2(1:numel(f2(1).pts(:,3)),:);
Ind = Ind + floor(size(P,1)/5);
disp('2 of 5 sorted...');
[f3,ind, ~] = Non_dominated_sorting(P(Start:Ind,1:end),ica,M);
p3=P(Start:Ind,1:end);
p3=p3(ind,:);
p3 = p3(1:numel(f3(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(P,1)/5);
disp('3 of 5 sorted...');
[f4,ind, ~] = Non_dominated_sorting(P(Start:Ind,1:end),ica,M);
p4=P(Start:Ind,1:end);
p4=p4(ind,:);
p4 = p4(1:numel(f4(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(P,1)/5);
disp('4 of 5 sorted...');
[f5,ind, ~] = Non_dominated_sorting(P(Start:Ind,1:end),ica,M);
p5=P(Start:Ind,1:end);
p5=p5(ind,:);
p5 = p5(1:numel(f5(1).pts(:,3)),:);
disp('5 of 5 sorted...');
R = p1;
R(size(R,1)+1:size(R,1)+size(p2,1),:) = p2;
R(size(R,1)+1:size(R,1)+size(p3,1),:) = p3;
R(size(R,1)+1:size(R,1)+size(p4,1),:) = p4;
R(size(R,1)+1:size(R,1)+size(p5,1),:) = p5;

Ind = floor(size(R,1)/3);
Remainder = mod(size(R,1),3);
Start = 1;
[f1,ind,~] = Non_dominated_sorting(R(Start:Ind,1:end),ica,M);
p1=R(Start:Ind,1:end);
p1=p1(ind,:);
p1 = p1(1:numel(f1(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(R,1)/3);
disp('1 of 3 sorted...');
[f2,ind, ~] = Non_dominated_sorting(R(Start:Ind,1:end),ica,M);
p2=R(Start:Ind,1:end);
p2=p2(ind,:);
p2 = p2(1:numel(f2(1).pts(:,3)),:);
Start = Ind+1;
Ind = Ind + floor(size(R,1)/3);
disp('2 of 3 sorted...');  
[f3,ind, ~] = Non_dominated_sorting(R(Start:Ind,1:end),ica,M);
p3=R(Start:Ind,1:end);
p3=p3(ind,:);
p3 = p3(1:numel(f3(1).pts(:,3)),:);
disp('3 of 3 sorted...');
X = p1;
X(size(X,1)+1:size(X,1)+size(p2,1),:) = p2;
X(size(X,1)+1:size(X,1)+size(p3,1),:) = p3;
[fX,ind,~] = Non_dominated_sorting(X,ica,M);
X=X(ind,:);
X = X(1:numel(fX(1).pts(:,3)),:);
disp('done...');
f = X;
end